#!/bin/bash
# =============================================================
#  Gym Kiosk Pi Setup — run this on a fresh Raspberry Pi
#
#  Usage:
#    curl -sL http://SERVER:9008/api/pi-setup/DEVICE_KEY | sudo bash
#
#  Or manually:
#    sudo bash setup.sh SERVER_URL DEVICE_KEY
#
#  Example:
#    sudo bash setup.sh http://192.168.1.8:9008 83875f18-500e-4ab9-b9d5-15e7f1c2a204
# =============================================================

set -e

SERVER="${1:-__SERVER__}"
DEVICE_KEY="${2:-__DEVICE_KEY__}"
INSTALL_DIR="/opt/kiosk"

# ---- Validate ----
if [[ "$SERVER" == "__SERVER__" ]] || [[ "$DEVICE_KEY" == "__DEVICE_KEY__" ]]; then
    echo "ERROR: SERVER and DEVICE_KEY are required."
    echo "Usage: sudo bash setup.sh http://YOUR_SERVER:9008 YOUR_DEVICE_KEY"
    exit 1
fi

echo "============================================="
echo "  Gym Kiosk Pi Setup"
echo "  Server:     $SERVER"
echo "  Device Key: ${DEVICE_KEY:0:8}..."
echo "============================================="

# ---- 1. Install system packages ----
echo "[1/7] Installing system packages..."
apt-get update -qq
apt-get install -y -qq usbrelay python3-pip python3-flask > /dev/null 2>&1
pip3 install evdev requests --break-system-packages -q 2>/dev/null || pip3 install evdev requests -q

# ---- 2. Create install directory ----
echo "[2/7] Setting up $INSTALL_DIR..."
mkdir -p "$INSTALL_DIR"

# ---- 3. Download scripts from server ----
echo "[3/7] Downloading kiosk scripts..."
curl -sf "$SERVER/api/pi-files/relay_service.py" -o "$INSTALL_DIR/relay_service.py"
curl -sf "$SERVER/api/pi-files/kiosk_scanner.py" -o "$INSTALL_DIR/kiosk_scanner.py"
echo "  Downloaded relay_service.py and kiosk_scanner.py"

# ---- 4. Write config ----
echo "[4/7] Writing config to /etc/kiosk.conf..."
cat > /etc/kiosk.conf << CONF
# Gym Kiosk Configuration — generated by setup.sh
KIOSK_SERVER=$SERVER
KIOSK_DEVICE_KEY=$DEVICE_KEY
KIOSK_RELAY_URL=http://localhost:5555/trigger
CONF

# ---- 5. USB relay permissions (no sudo needed at runtime) ----
echo "[5/7] Setting USB relay permissions..."
cat > /etc/udev/rules.d/99-usbrelay.rules << UDEV
SUBSYSTEM=="usb", ATTR{idVendor}=="16c0", ATTR{idProduct}=="05df", MODE="0666"
UDEV
udevadm control --reload-rules
udevadm trigger

# ---- 6. Create systemd services ----
echo "[6/7] Creating systemd services..."

cat > /etc/systemd/system/relay.service << SVC
[Unit]
Description=Kiosk Relay Service
After=network-online.target
Wants=network-online.target

[Service]
ExecStart=/usr/bin/python3 $INSTALL_DIR/relay_service.py
Restart=always
RestartSec=3

[Install]
WantedBy=multi-user.target
SVC

cat > /etc/systemd/system/scanner.service << SVC
[Unit]
Description=Kiosk QR Scanner
After=network-online.target relay.service
Wants=network-online.target

[Service]
ExecStart=/usr/bin/python3 $INSTALL_DIR/kiosk_scanner.py
EnvironmentFile=/etc/kiosk.conf
Restart=always
RestartSec=3

[Install]
WantedBy=multi-user.target
SVC

systemctl daemon-reload
systemctl enable relay scanner
systemctl restart relay scanner

# ---- 7. Verify ----
echo "[7/7] Verifying..."
sleep 2

RELAY_OK=$(systemctl is-active relay)
SCANNER_OK=$(systemctl is-active scanner)

echo ""
echo "============================================="
echo "  Setup complete!"
echo "  Relay service:   $RELAY_OK"
echo "  Scanner service: $SCANNER_OK"
echo "============================================="

if [[ "$RELAY_OK" == "active" ]] && [[ "$SCANNER_OK" == "active" ]]; then
    echo "  All services running. Kiosk is ready!"
    echo "  Plug in DS reader + USB relay and scan a QR code."
else
    echo "  WARNING: Some services failed to start."
    echo "  Check: sudo journalctl -u relay -u scanner --no-pager -n 20"
fi
echo ""
